Master
TeamFarce/Lorem-Ipsum pull request #16
Opened 2017-02-15 23:42 UTC by jacobsax

Added a journal, a personality level indicator and updated the current
score indicator so that this works correctly.

2017-02-15 23:48 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +
Random pointless newline

2017-02-15 23:50 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Journal.java
> +    SpriteBatch batch;
Missing visibility specifier.

2017-02-15 23:51 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Journal.java
> +        //Gdx.input.setInputProcessor(stage);
This should be removed

2017-02-15 23:51 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Clues.java
> +    public void updateMain(){
SPAAAAAAAAAAAACE. (`updateMain() {`)

2017-02-15 23:52 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Clues.java
> +    {
Brace should be on the same line.

2017-02-15 23:52 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
>      {
Could move the brace to this line since we're changing this line.

2017-02-15 23:53 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +        {
Move this brace up a line.

2017-02-15 23:53 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +            {
Move this brace up a line.

2017-02-15 23:54 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Clues.java
> +    {
Brace should be on the same line.

2017-02-15 23:55 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Journal.java
> +    public Skin initSkin(){
SPAAAAAAAAAAAACE. (`initSkin() {`)

2017-02-15 23:56 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Journal.java
> +    public void updateMain(){
SPAAAAAAAAAAAACE. (`updateMain() {`)

2017-02-15 23:56 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Journal.java
> +    {
Brace should be on the same line.

2017-02-15 23:56 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Journal.java
> +    {
Brace should be on the same line.

2017-02-15 23:57 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Notepad.java
> +    public Stage initNotepad(){
SPAAAAAAAAAAAACE. (`initNotepad() {`)

2017-02-15 23:57 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Notepad.java
> +    {
Brace should be on the same line.

2017-02-15 23:57 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Notepad.java
> +    {
Brace should be on the same line.

2017-02-15 23:58 UTC, Comprs commented on game/core/src/me/lihq/game/screen/JournalScreen.java
Unneeded space

2017-02-16 00:17 UTC, jacobsax commented
Journal:
- Added collected clues view
- Added notepad
- Added close button

Navigation Screen:
- Added personality score
- Fixes Score

2017-02-16 00:26 UTC, Comprs requested changes
Could still do with more comments

2017-02-16 00:26 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +    public void updateMain(){
Space between the bracket and brace missing

2017-02-16 00:26 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
>      {
Could move the brace up since this line is being changed

2017-02-16 00:26 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Clues.java
> +    Skin uiSkin;
Missing visibility specifiers

2017-02-16 00:26 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +        {
Move the brace up a line

2017-02-16 00:27 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +        {
not doing that

2017-02-16 00:27 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +    public void updateMain(){
will do that

2017-02-16 00:27 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
>      {
will do that

2017-02-16 00:27 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/journal/Clues.java
> +    Skin uiSkin;
will do that

2017-02-16 00:30 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +    public void updateMain(){
changed

2017-02-16 00:30 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +        {
It was done for line 78 in game/core/src/me/lihq/game/screen/elements/journal/Clues.java

2017-02-16 00:30 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
>      {
changed

2017-02-16 00:30 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +            {
This brace could be moved up.

2017-02-16 00:31 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/journal/Clues.java
> +    Skin uiSkin;
done

2017-02-16 00:32 UTC, Comprs commented on game/core/src/me/lihq/game/screen/elements/journal/Clues.java
> +        for (Clue clue : this.game.player.collectedClues){
Space between last bracket and brace

2017-02-16 00:33 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +        {
done

2017-02-16 00:33 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/StatusBar.java
> +            {
done

2017-02-16 00:34 UTC, jacobsax commented on game/core/src/me/lihq/game/screen/elements/journal/Clues.java
> +        for (Clue clue : this.game.player.collectedClues){
done

2017-02-16 00:45 UTC, merged